### ISSUE TITLE
TS.5.a: Prototype name resolution services - synonym files

### ISSUE THREAD

**Issue by mmersmann** [TranslatorIIPrototypes/NameResolution#2]
Kent to deliver synonym files to Patrick.

Related:
[TS.5: Prototype name resolution services](https://github.com/TranslatorIIPrototypes/NameResolution/issues/1)
[TS.5.b: Prototype name resolution services - infrastructure](https://github.com/TranslatorIIPrototypes/NameResolution/issues/3)
[TS.5.c: Prototype name resolution services - broaden scope](https://github.com/TranslatorIIPrototypes/NameResolution/issues/4)

**Comment by kshefchek** [comment]
closed via https://github.com/TranslatorIIPrototypes/sandbox/commit/5147da070724dc2b2ff8f0468951dd548a46ffdd
