### ISSUE TITLE
Return all names?

### ISSUE THREAD

**Issue by cbizon** [TranslatorIIPrototypes/NameResolution#9]
Currently if I look up a term that has many synonyms, I get back the identifiers, and then the list of lexical synonyms for that entity, but if I use different query terms, I get back different lists of names.  I suspect that it's the list that solr decided matched my query, but I'm not sure.

Should we get all the names back?  Maybe the matches are marked somehow?   It might be useful in determining which of multiple entities that come back are the one(s) that you want.

Example: "Parkinson 19" returns 10 synonyms for MONDO:0014231 but "Parkinson 19 early" only returns 1.

**Comment by patrickkwang** [comment]
Yes, we should get all names back.
